// Bundles the sandboxed player runtime (src/player/runtime) into one script
// string that the /play route inlines with a CSP hash (ADR 0007). Run by
// `npm run player:build`; `check`, `build` and `dev` run it first so the
// generated module is always fresh. The output is committed.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "src", "player", "runtime", "index.ts");
const out = join(root, "src", "player", "runtime.generated.ts");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
  tsconfig: join(root, "tsconfig.json"),
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "warning",
});

const js = result.outputFiles[0].text;
const hash = createHash("sha256").update(js).digest("base64");
const previous = (() => {
  try {
    return readFileSync(out, "utf8");
  } catch {
    return "";
  }
})();

const banner = `/* eslint-disable */
// GENERATED by scripts/build-player.mjs — do not edit. Source: src/player/runtime/.
// The sandboxed player runtime as one script, plus the base64 sha256 the /play route
// puts in its Content-Security-Policy (script-src 'sha256-…').
`;
const content = `${banner}export const PLAYER_RUNTIME = ${JSON.stringify(js)};
export const PLAYER_RUNTIME_SHA256 = ${JSON.stringify(hash)};
export const PLAYER_RUNTIME_BYTES = ${Buffer.byteLength(js)};
`;

if (content !== previous) {
  writeFileSync(out, content);
  console.log(
    `player runtime: ${(Buffer.byteLength(js) / 1024).toFixed(1)} KiB, sha256 ${hash.slice(0, 12)}… (updated)`,
  );
} else {
  console.log(`player runtime: ${(Buffer.byteLength(js) / 1024).toFixed(1)} KiB, unchanged`);
}
